Doc: Add description of PEtab development process
PEtab-dev/PEtab pull request #507
Opened 2021-02-17 15:43 UTC by dweindl

As agreed on by the PEtab authors.

2021-03-02 10:07 UTC, fbergmann commented on doc/development.rst
> +shall be made using GitHub issues. Benefits, problems and potential
i would add a comma: "problems, and "

2021-03-02 10:07 UTC, fbergmann commented on doc/development.rst
> +* the new version of the specifications are deposited at Zenodo
should it be "the new version ... is deposited at zenodo" .. rather than are?

2021-03-02 10:10 UTC, dweindl commented on doc/development.rst
> +* the new version of the specifications are deposited at Zenodo
```suggestion
* the new version of the specifications is deposited at Zenodo
```

2021-03-02 10:21 UTC, dweindl commented on doc/development.rst
> +shall be made using GitHub issues. Benefits, problems and potential
```suggestion
shall be made using GitHub issues. Benefits, problems, and potential
```

2021-03-02 13:22 UTC, svenjakemmer requested changes

2021-03-02 13:22 UTC, svenjakemmer commented on doc/development.rst
> +
In the email announcing the editors we had the phrase: "(1 year, with the option of +1 year if one of the above editors hands over his responsibility)"
Should we include this in the document? Something like
```suggestion
If an editor decides to hand over his editorial role before his election period expires, editors elected for a shorter time period can decide to take over and expand their time as an editor for the remaining time.
```

2021-03-02 16:02 UTC, FFroehlich approved these changes

2021-03-02 16:02 UTC, FFroehlich commented on doc/development.rst
> +top 5 candidates, there will be run-off elections between those candidates
```suggestion
top 5 candidates, there would have been run-off elections between those candidates
```

2021-03-02 16:02 UTC, FFroehlich commented on doc/development.rst
> +with equal numbers of votes. The editors-elect are given 3 working days to
```suggestion
with equal numbers of votes. The editors-elect were given 3 working days to
```

2021-03-02 16:04 UTC, FFroehlich commented
I think first special election is something that already happened and will not apply to future events. Accordingly, this should be  described in past tense.

2021-03-02 20:28 UTC, FFroehlich commented on doc/development.rst
> +The first election was be held among the authors of the original PEtab
```suggestion
The first election was held among the authors of the original PEtab
```

2021-03-03 09:26 UTC, svenjakemmer approved these changes
Sounds good to me now :)

2021-03-05 17:47 UTC, merged