WIP: Specification of Timecourses
PEtab-dev/PEtab pull request #581
Opened 2024-05-22 09:27 UTC by fbergmann

This draft PR adds the descriptions from the [Time course specification](https://docs.google.com/document/d/1Uo0mtU8Tb6m0yZc-A-NprDXeS-9ZDYPA8U3Y_aChqEM/edit) to the `release/2.0.0` branch.

2024-05-30 13:24 UTC, dweindl commented on doc/documentation_data_format.rst
> +    Expressions containing more than a single parameter ID or numberical
```suggestion
    Expressions containing more than a single parameter ID or numerical
```

2024-05-30 13:24 UTC, dweindl commented on doc/documentation_data_format.rst
> +The optional time courses tabke describes a sequence of different experimental
```suggestion
The optional time courses table describes a sequence of different experimental 
```

2024-12-05 12:43 UTC, dweindl commented
Resolved merge conflicts. 

This needs to be updated to match the new mostly-agreed-upon format in https://github.com/PEtab-dev/PEtab/issues/586 (changed experiments table, changed conditions table).

2025-02-05 13:51 UTC, FFroehlich requested changes

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +| STRING       | [STRING]         | MODEL_ENTITY_ID  | STRING          | MATH_EXPRESSION    |
```suggestion
| PETAB_ID       | [STRING]         | NON_ESTIMATED_ENTITY_ID  | STRING          | MATH_EXPRESSION    |
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``observableId`` [STRING, REQUIRED, REFERENCES(observables.observableID)]
```suggestion
- ``observableId`` [PETAB_ID, REQUIRED, REFERENCES(observables.observableID)]
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +| observableId | experimentID | NUMERIC     | NUMERIC\|inf |
```suggestion
| PETAB_ID | PETAB_ID | NUMERIC     | NUMERIC\|inf |
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``experimentId`` [STRING, REQUIRED, REFERENCES(experimentsTable.experimentID)]
```suggestion
- ``experimentId`` [[PETAB_ID], REQUIRED, REFERENCES(experimentsTable.experimentID)]
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +  Time point of the measurement in the time unit specified in the SBML model,
Would consider it to be less confusing if ``inf`` was considered a numeric value here.

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +| PETAB_ID            | NUMERIC or '-inf' | CONDITION_ID    |
NUMERIC or '-inf', see above.

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``experimentId`` [STRING, REQUIRED]
```suggestion
- ``experimentId`` [PETAB_ID, REQUIRED]
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +  in the model. ``-inf`` indicates pre-equilibration (e.g., for drug
```suggestion
  in the model. ``-inf`` indicates that the respective condition will be simulated until a steady state is reached.
```

Strictly speaking equilibration would only be possible for models that satisfy detailed balance, would therefore prefer to avoid using (incorrect) jargon here.

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``CONDITION_ID``: Reference to a condition ID in the condition table that
[PETAB_ID, REQUIRED, REFERENCES(conditions.conditionID)]

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``parameterId`` [STRING, REQUIRED]
```suggestion
- ``parameterId`` [PARAMETER_ID, REQUIRED]
```

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +  in the model. ``-inf`` indicates pre-equilibration (e.g., for drug
**TODO**, behaviour if there is no steady state?

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
While I agree that we can drop the name in the conditions table, I think it would be nice to have an optional name column here.

2025-02-05 13:51 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``petabEntityId`` [STRING, REQUIRED]
```suggestion
- ``petabEntityId`` [PETAB_ID, REQUIRED]
```

2025-02-06 23:58 UTC, dilpath reviewed
Thanks, I'm happy to review this again after the current feedback round

2025-02-06 23:58 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +    other row  with the same ``conditionId`` in the conditions table.
```suggestion
    For any ``conditionId`` with ``operationType=noChange``, there must not be any
    other row with the same ``conditionId`` in the conditions table.
```

2025-02-06 23:58 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +| PETAB_ID            | NUMERIC or '-inf' | CONDITION_ID    |
Agreed, in the measurements table it is `NUMERIC\|inf` instead

2025-02-06 23:58 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  evaluated *after* ``condition_B`` was applied.
This is the old (not long format) version of the experiments table, so it might be confusing to users

```suggestion
  Note: The time interval in which a condition is applied includes the
  respective starting timepoint, but excludes the starting timepoint of
  the following condition. This means that for an experiment where
  ``condition_A`` is applied at ``time_A`` and later ``condition_B`` is
  applied at ``time_B``, then ``condition_A`` is active
  during the interval ``[time_A, time_B)``. This implies that any event
  assignment that triggers at ``time_B`` will occur *after* ``condition_B`` was
  applied and for any measurements at ``time_B``, the observables will be
  evaluated *after* ``condition_B`` was applied.
```

2025-02-06 23:58 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +**TODO** how to deal with conflicts?
Suggestion based on previous conversations, not sure how to word it best though
```suggestion
Multiple conditions can be applied at the same time point by specifying
multiple lines with the same ``experimentId`` and ``time`` but different
``conditionId``. The order of the conditions is arbitrary.

All changes across all simultaneous conditions are applied in order of
dependencies, with conservation of mass when volumes change, i.e.
a volume change implies a concentration change, but not vice versa.

Hence, volume changes are applied before concentration changes in the
same compartment, and changes to parameters are applied before
changes to species that depend on the parameters.
```

2025-02-11 08:30 UTC, dweindl commented
Thanks for the feedback.

2025-02-11 08:31 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  (:ref:`math_expressions`, overriding values in the condition table, etc.)
To be updated once all changes here have been finalized.

2025-02-11 08:36 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  Time point of the measurement in the time unit specified in the SBML model,
"Finite numeric value or `inf`"? Since `-inf` would not be allowed?

2025-02-11 08:39 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
Fine to add `experimentName` here if we drop the condition names. However, if we want to keep condition names, which then would have to be specified in some other place (yaml, annotations table, ...?), I would collect all of that in the same place.

2025-02-11 08:46 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  in the model. ``-inf`` indicates pre-equilibration (e.g., for drug
Agreed. Any ideas for a more concise but still correct term?

In case of no steady state: `inf` objective value?

Do we want to specify any steady state criteria? We don't do that for integration accuracy and so on, but it feels problematic to not say anything here. We could suggest something like `dx/dt < 100 * integration_tolerance`?

2025-02-11 09:13 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +Each line specifies a change of one specific property of a specific entity.
This hides the fact that a single entity has different types of associated values (e.g., current value vs. rate) and excludes "symbolic assignment" like `setAssignment`, doesn't it?

2025-02-11 09:56 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  type of the model.
> > This may an entity defined in the model, or an alias from the mapping
> > table.
> 
> `NON_ESTIMATED_ENTITY_ID` is already defined, so could move this statement about the mapping table to that definition.

:+1: 

> > The entity must be uniquely identifiable.
> 
> Do you have an example for why it's useful to state this here? Local parameters of SBML reactions might be? Still this is part of the definition of `NON_ESTIMATED_ENTITY_ID` I think, so could be moved there.

Can be moved there. Right, local parameters would be an example.

> > Parameters from the :ref:`parameters_table` are not allowed here.
> 
> Why can't I change the value of a non-estimated parameter that is in the parameter table? Fine for me, but now this also contradicts the definition of `NON_ESTIMATED_ENTITY_ID`, which explicitly supports parameter table parameters.

That wasn't allowed so far, and I would find it very confusing. Unlike SBML-parameters, PEtab parameters were always assumed to be constant throughout time and conditions. I would strongly prefer keeping it that way. Right, currently this is contradictory and `NON_ESTIMATED_ENTITY_ID` needs to be updated.

2025-02-11 15:18 UTC, sebapersson commented on doc/v2/documentation_data_format.rst
> +**TODO: keep conditionName or not?**
conditionName I think can be kept as optional as it can help with nicer plotting.

2025-02-12 14:00 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +  - ``setRate``: The time-derivative of the target is set to ``targetValue``
Yeah, that sounds like it would be helpful to introduce `targetValue` in favour of having `addTo`, `multiply`, etc.

Why would we need operators like `rateOf`, `rateExpressionOf`? I don't see why one would ever transfer information from rate to value and everything else should be achievable one way or another.

Also, what about using `setValue` in favor of `setCurrentValue`?

2025-02-12 16:05 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  type of the model.
> That wasn't allowed so far, and I would find it very confusing. Unlike SBML-parameters, PEtab parameters were always assumed to be constant throughout time and conditions. I would strongly prefer keeping it that way. Right, currently this is contradictory and `NON_ESTIMATED_ENTITY_ID` needs to be updated.

Yes, you're right, makes sense :+1:

2025-02-12 16:47 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +      ``A``, the change in quantity A should be applied first such that the
> This is not how SBML work right?
> 
> If I remember correctly if both `A` and `B` are assigned something in an event, basically the pre-event `A` and `B` values are used unless priority is specified.

I'm not sure, all I see in the SBML spec is (regarding simultaneously-occurring events)
> A given simulator may use any algorithm to choose an order as long as every event is executed exactly once.

This choice of compartment priority (and more generally to respect the dependency graph) is partly based on discussions with @matthiaskoenig last year -- perhaps @matthiaskoenig can say more here?

2025-02-12 17:36 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +      ``A``, the change in quantity A should be applied first such that the
There is a difference between simultaneously occuring events and simultaneous assignments during the same event. I would treat assignments via conditions the same as a single event, i.e. not subject to priority or useValuesFromTriggerTime attributes. I would propose to not follow the dependency graph (and rather simply use pre-assignment values) with the exception of compartments. As done with SBML Event Assignments (even though this isn't crystal clear in the sbml spec).

For example it might make sense to average two species A = B = (A + B)/2. Due to circularity, this assignment is not possible when following the dependency graph, but straightforward with pre-change values. Following of dependencies can always be reproduces through substitution.

2025-02-12 17:43 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +    (symbolically).
No, this is discussed after Differential/Algebraic/Constant targets are introduced. To my understanding, structural alterations are not allowed.

2025-02-14 10:24 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
In that case I would propose to move all names (including observables etc) to such a table. Would anyways be nice as it would introduce the possibility of, e.g. naming states.

2025-02-19 08:56 UTC, matthiaskoenig commented
In the timecourses, what we essentially have are event assignments triggered at t=t_trigger​. All event assignments must be executed simultaneously—this is not a step-by-step process. Instead, the model state must transition to the new state all at once. Any mathematical expressions that depend on updated parameters, compartments, or species must be re-evaluated accordingly. In other words, all changes are applied in a single step, and the AST (Abstract Syntax Tree) affected by these changes is fully re-evaluated. There is no predefined execution order—it is a single transformation of the model state.

Therefore, the claim that "compartment has priority" is incorrect and does not make sense. The underlying issue is that PETab changes are not clearly defined and have been incorrectly implemented by simulators. As seen in cases where changes affect both compartment volumes and concentrations, many simulators apply these changes sequentially, which is incorrect. Instead, all triggered changes must be applied in a single step. This clarification should also be explicitly stated for changes applied outside of timecourses.

Additionally, in SBML, there is a flag called useValuesFromTriggerTime, which allows the use of values before the assignments. This is likely what you are referring to:

> The time of assignment is not affected by the Event attribute useValuesFromTriggerTime—that attribute affects the time at which the EventAssignment’s math expression is evaluated. In other words, SBML allows decoupling the time at which the variable is assigned from the time at which its value expression is calculated.

2025-02-19 08:59 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +      ``A``, the change in quantity A should be applied first such that the
We want 2 different behaviors. These are managed in SBML events via the ` useValuesFromTriggerTime` flag. So we need probably this flag on the timecourse to ensure both scenarios are possible (see also comment below)

2025-02-19 09:29 UTC, matthiaskoenig commented
In SBML, all ListOf constructs are unordered lists. This means an SBML model can be modified by shuffling any ListOf elements, such as ListOfEventAssignments, without affecting the numerical results of a simulation. In other words, there is no inherent order in these lists, nor are there execution priorities—except in cases where ordering is necessary, in which attributes like priority have been introduced to dictate the execution of multiple Events.

The same principle should apply when multiple changes are made in PETab: all changes should be applied simultaneously. If ordering is required, an explicit order or priority attribute must be introduced. If mathematical expressions need to reference values from the end of the previous time span, a useValuesFromTriggerTime mechanism is necessary. For cases where a mix of behaviors is needed, an Event-like construct could be introduced, allowing assignments to be grouped and prioritized.

There is a reason SBML Events are complex. Either we adopt a full event-based approach where changes can be triggered after each time span, or we adhere to a simpler default approach where all changes are applied simultaneously.

One concern is that specifications often end up reflecting existing implementations rather than defining a general, correct solution. This appears to be happening here, as most PETab implementations currently apply changes sequentially. This approach is likely incorrect, but since the specification does not clearly define the intended behavior, there is uncertainty. Moreover, it does not align with what users of SBML models would expect.

2025-02-19 10:09 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +**TODO: keep conditionName or not?**
The problem is that now there may be several rows per condition, which makes it not so ideal to specify any condition names there. Would you still keep it that table? Would all rows for that condition have to have the same value, or should there only be one non-empty entry per condition?

2025-02-19 10:16 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +    (symbolically).
We might have different understandings of "structural alterations". Changing some algebraic expression `e := x` to `e := y` would be allowed, but changing some differential state to some algebraic expression would not be allowed. In how much that requires building different models is probably very much implementation dependent.

2025-02-19 13:39 UTC, sebapersson commented on doc/v2/documentation_data_format.rst
> +    (symbolically).
> We might have different understandings of "structural alterations". Changing some algebraic expression e := x to e := y would be allowed, but changing some differential state to some algebraic expression would not be allowed. In how much that requires building different models is probably very much implementation dependent.

Thanks for clarification, just a last question to fully understand. So if we have a parameter given via an assignment rule; `k = k1 * k2` would it then be allowed to change `k` via `setAssignment`?

2025-02-21 08:23 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +    (symbolically).
Yes, that was to my understanding the (only) use case for `setAssignment`.

2025-02-26 15:27 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  - ``setRate``: The time-derivative of the target is set to ``targetValue``
One use case where one might want to use both the current value and the rate expression could be some piecewise definition of a rate expression where the condition depends on the current state. I'd don't consider super important.

2025-02-26 16:02 UTC, dweindl commented
> since the specification does not clearly define the intended behavior, there is uncertainty

Right. That definitely needs to be addressed.

> what users of SBML models would expect

To be honest, I am not sure for how many SBML users the users' expectations match the SBML standard when it comes to event assignments. I am still regularly confused when it comes to simultaneous changes in compartment sizes and concentrations.
That was one reason why considered different options, such as the compartment-change-first approach.
I'd find some explicit priority the most intuitive and least error-prone. This would in my opinion also cause the least issues with non-SBML models, where the interpretation or dependent/independent quantity is maybe less clear.

2025-02-26 22:41 UTC, matthiaskoenig commented
The main issue with establishing a fixed order for updating multiple variables (such as compartments, species, or parameters) is that mathematical calculations dependent on these variables could produce unexpected results depending on the update sequence.

For example, consider a compartment V and a concentration C. Any calculation that relies on both V and C may yield different outcomes depending on the update order. Suppose we start with V=1 and C=1, then update both to V=10 and C=10. If there is a calculation dependent on the relationship between V and C, the result will vary based on the order in which they are updated. For instance, an event triggered when V>C will only occur if V is updated before C. If C is updated first or both are updated simultaneously, the event may not trigger, leading to inconsistencies.

In other words, updating variables sequentially in a fixed order can lead to intermediate steps that place the model in an undefined state. This issue persists regardless of the specific order. Therefore, it is essential to either update all variables synchronously or clearly define and follow a predetermined update sequence for each variable to maintain a consistent model state (simply updating compartments before species does not resolve the issue).

The issue with the concentrations is just one of such a problem because species concentrations depend on their compartment volumes, so there is a math dependency linking C and V which depends on the order. But there can be many such dependencies in the math of the model.

2025-02-27 07:24 UTC, dweindl commented
Okay, fair point. The intermediate model states would be problem.

2025-02-27 12:28 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +      ``A``, the change in quantity A should be applied first such that the
I'd vote for @FFroehlich's suggestion here.

2025-03-12 16:20 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +    any other row with the same ``conditionId`` in the conditions table.
@FFroehlich suggested to completely remove `operationType` because after the recent simplification.  

`noChange` would then be specified by an empty conditionID in the experiments table.

Works for me.

@PEtab-dev/petab-editors : What are your thoughts?

2025-03-13 15:39 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  may improve human readability.
```suggestion
  Multiple conditions cannot be applied simultaneously in a single experiment,
  i.e. the ``time`` values must be unique for each ``experimentId``.
  The order of the rows is arbitrary, but specifying the rows in ascending order
  of time may improve human readability.
```

2025-03-13 16:17 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
Shall we repurpose the mapping table for that? I.e. adding a `name` / `label` column there and allowing empty `modelEntityId`? This could also be a place for adding additional annotations, such as SBO terms.

Alternatively, adding that to the yaml file. I'd avoid another additional table.

2025-03-13 16:25 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +**TODO: keep conditionName or not?**
To be continued at https://github.com/PEtab-dev/PEtab/pull/581/files#r1993877029; marking this as resolved.

2025-03-17 17:54 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +a volume change implies a concentration change, but not vice versa.
```suggestion
All changes defined in the condition table are applied in two consecutive phases, similar to events in SBML.

1. **Evaluation of ``targetValues``**  
   ``targetValues`` are first evaluated using the *current*values of all variables in the respective expression.  
   - For the initial time period of an experiment, *current* values are determined by the initial conditions defined in the model.  
   - For subsequent time periods, the *current* values are defined by the simulation results at the end of the preceding time period.  

2. **Assignment and Update of Derived Variables**  
   Once evaluated, all ``targetValues`` are simultaneously assigned to their corresponding ``targetId``s, and derived variables are updated accordingly.  
   - This means that values of variables assigned by SBML assignment rules or PYSB expressions will need to be re-evaluated.  
   - Notably, for SBML models — where concentrations are always treated as derived variables — species with ``hasOnlySubstanceUnits=false`` and simultaneous changes to concentration and compartment volume in the condition table will have their amount and compartment volume updated first, with the resulting concentration computed as the fraction of amount to volume. For further details, refer to SBML semantic test suite case  
`01779 <https://github.com/sbmlteam/sbml-test-suite/blob/7ab011efe471877987b5d6dcba8cc19a6ff71254/cases/semantic/01779/01779-model.m>`_.
```

2025-03-17 19:40 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +a volume change implies a concentration change, but not vice versa.
Thanks, looks good. I'd only add some explanation similar to the one provided in the test case directly here. I'll commit the suggestion to make it easier for others to propose changes if necessary.

2025-03-17 21:52 UTC, dilpath commented
The suggestion for the reinitialization looks good to me. I could separate step 2 into "petab changes" and "model changes", if you agree. Here's a suggestion, that also includes some other details that we discussed.

```md
All changes defined in the condition table are applied in two consecutive phases, similar to events in SBML. The changes take precedence over other changes that may be encoded in the model, which occur in a third phase.

1. **Evaluation of ``targetValues``**
[...]

2. **Assignment of ``targetValues`` to ``targetIds``**  
All evaluated ``targetValues`` are simultaneously assigned to their corresponding ``targetId``s. It is invalid to apply more than one assignment to a single ``targetId`` simultaneously.

3. **Update of Derived Variables, Events and Finalization**
[...]
All other changes encoded in the model are now applied as well. For example, this includes SBML events. The model state for this timepoint is the model state after all of these changes, at the end of this phase.
```

2025-03-18 07:13 UTC, dweindl commented
> separate step 2

Thanks, I incorporated your suggestion with some modifications.

2025-03-18 15:19 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
One aspect I’m unsure about is how simple conditions (not part of a time course) are handled. I assumed that the Experiments table is required and that simple conditions would be treated via a time course with time = 0.

The Measurements table specifies that it requires experimentId ([PETAB_ID], REQUIRED, REFERENCES(experimentsTable.experimentID)), meaning it maps to experiments rather than conditions. So there would be a clarification how the simple cases of only conditions at time = 0 would be handled.

I would strongly prefer that the Experiments table is required. For an optimization problem one would need measurements which are linked to experiments and experiments require conditions. So both tables, conditions and experiments, are required. There can be the special case that both tables are empty in case of just mapping to the model as is without any changes.

2025-03-18 15:27 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
Personally, I don't have an issue with information being duplicated in long tables. I.e. having the same id and name multiple times. This is probably easier to understand then to moving things to the mapping table.
If we start doing that I would prefer a solution which handles more metadata then just names for ids. E.g. annotations to ontologies, arbitrary information fields, ...
E.g. a nice hashmap which allows to annotate identifiers: 
```
{
    id: "condition1",  # id, table required
    table: "condition",
    name: "My condition"  # additional optional fields
    description: "This condition does ..."
    conditionClass: "class 1 - dosing",
    ...
}
```
For me the mapping table feels like a bad hack and prefer the duplication, or a more generic solution which allows to store additional information which can be used by tools.

2025-03-19 09:42 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +Conditions table
I'd prefer introducing the independent tables before they are referenced by other tables (conditions, experiments, observables, measurements, parameters).

2025-03-19 09:52 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
So far, the experiment table is required, unless a simulation is to be performed with the default model settings.

If there is only a single condition that is described by the model, experimentId for the respective measurements may be empty and the experiment table as well as the conditions table may be omitted.

I'd find it somewhat annoying to create those empty files in that case, but I don't feel very strongly about it.

Other opinions?

2025-03-19 09:55 UTC, dweindl commented on doc/v2/gfx/petab_scope_and_files.png
I prefer introducing the conditionIds before they are used in the experiments table.

2025-03-19 11:21 UTC, matthiaskoenig commented on doc/v2/gfx/petab_scope_and_files.png
no strong feeling about this one

2025-03-19 11:27 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
I would prefer to have the experiments table required and have some way to fill out the conditions and experiments also for the special case of no changes. I.e. Having a row in the experiments table where the conditionId is empty (and an empty condition table). This would allow to use the value of the experimentId (experimentName) in plotting and analysis, ... . It is just a special case where the experiment has no changes.

2025-03-19 11:37 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
This option already exists, independent of requiring the experiment table. I.e. you can have a row in the experiment table with empty conditionId.

Also some experimentName could be provided there, or elsewhere (to be discussed, see other thread / mapping table).

2025-03-19 11:46 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
> If we start doing that I would prefer a solution which handles more metadata then just names for ids. E.g. annotations to ontologies, arbitrary information fields, ...

This would be possible that way. The mapping table can have arbitrary additional columns (`description`, `sboTerm`, whatever you like). I am just not sure if we should worry about those here, as long as there is no defined use of this information. The same is true for `name`, just that I would include that in the specs, since there was a way to specify that in PEtab v1.

> mapping table feels like a bad hack

I'd also prefer not having it, but I don't have a better alternative. It's a compromise we have to make to make this table-based definition work, while keeping the number of tables manageable and avoiding duplication.

2025-03-19 11:51 UTC, dweindl commented on doc/v2/gfx/petab_scope_and_files.png
Ok, bottom-up / top-down is a matter of taste. I'd leave it as is for now. This figure will have be updated a couple more times for PEtab v2 anyways. My main goal here was not displaying any incorrect information. I am fine with a complete makeover of that figure if somebody wants to take the time.

2025-03-19 12:34 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +| experimentId        | time              | conditionId     |
Sounds good to me. Then I am satisfied with the mapping table approach. 

We should not worry about these here. It would just be important that works in principle. I.e. use the mapping table to store additional information mapped on the ids which tools could use (mainly for visualization and communication).

2025-03-19 13:58 UTC, FFroehlich approved these changes

2025-03-19 13:58 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``modelEntityId`` [STRING, REQUIRED]
```suggestion
- ``modelEntityId`` [STRING or empty, REQUIRED]
```

2025-03-19 13:58 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +- ``name`` [STRING, OPTIONAL]
```suggestion
- ``name`` [STRING or empty, OPTIONAL]
```

2025-03-19 13:58 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +  reporting or visualization purposes.
Say that if no name is provided it defaults to the petabEntityId?

2025-03-19 14:07 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +values of species, and compartments, during specific time periods.
I find it a bit difficult. I already find the term "condition" a bit problematic, which basically describes a set of discrete changes. A "period" is the time between applying some condition and applying the next condition, or the end of the simulation. They aren't really interchangeable.

2025-03-19 14:19 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +   updated. If the model format has a concept of species and compartments,
It can be combined with the previous step, but I think it's not the same. The one thing is updating the basic model state, and the other one, re-evaluating any dependent constructs. With concentration-species, this is distinction is a bit blurred, though.

I wouldn't say it's wrong for PySB models. If there are no concentrations to update, then this is simple skipped.

2025-03-19 14:21 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +5. **Evaluation of Observables**
I found it more suitable here, but it's probably good to add a reference.

2025-03-19 14:22 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  the same experiment, the same noise model,
That sentence continues on the next line.

2025-03-19 14:24 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  This grouping makes it possible to use the plotting routines that are
The latter. I'd keep that for elsewhere. I don't think we should refer to the petab library here, but that's out of scope.

2025-03-19 14:25 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  :ref:`v2_reinitialization_semantics`.
Agreed. Yes, good to clarify that.

2025-03-19 14:29 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  reporting or visualization purposes.
Fine to add, but it's anyways not clear where exactly it would be used.

2025-03-19 14:35 UTC, dweindl commented on doc/v2/documentation_data_format.rst
>  - A grouping file that lists all of the files and provides additional information
In terms of importance, yes. But it will be unclear which files we are referring to.

2025-03-19 14:37 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +| conditionId  | targetId                | targetValue        |
Remove or add examples everywhere?

2025-03-19 15:01 UTC, dweindl commented on doc/v2/gfx/petab_files.png
> Mappings should appear (I am not sure what this is and what it is good for?)

I left those out, because I guess that most users won't really need them, and it's hard to guess it's use from the figure.

> Probably the "Parameter transformations" should be removed, because as I remember these should be removed from the paramters table.

Correct, but that will be addressed in a separate PR. It's still in the spec for now.

Thanks for the suggestions. Let's update the rest once PEtab v2 is mostly complete.

2025-03-19 15:02 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +Any changes applied to the model will remain in effect until they are changed
Probably best to drop it here, there is a more detailed description about model state/structure further below anyways.

2025-03-19 15:02 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
@PEtab-dev/petab-editors / all: Optional or mandatory experiments table?

2025-03-19 15:12 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +   updated. If the model format has a concept of species and compartments,
Ah I see, will make a proposal how to split the description then. I think this will also make it more evident what's actually going on with SBML concentrations/volumes.

2025-03-19 15:29 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +     `01779 <https://github.com/sbmlteam/sbml-test-suite/blob/7ab011efe471877987b5d6dcba8cc19a6ff71254/cases/semantic/01779/01779-model.m>`_.
```suggestion
   * These assignments respect language specific interpretations of what variables are *atomic* and which are *derived* or *algebraic*. Most notably, SBML considers species amounts and compartment size but **not** concentrations to be *atomic*. This means that for any entry that has a ``targetId`` that refers to a species with ``hasOnlySubstanceUnits=false`` will have it's ``targetValue`` (interpreted as concentration) converted to amounts using the **current** compartment size and then applied to the ``targetId``s amount. For further details, refer to SBML semantic
     test suite case `01779 <https://github.com/sbmlteam/sbml-test-suite/blob/7ab011efe471877987b5d6dcba8cc19a6ff71254/cases/semantic/01779/01779-model.m>`_.
```

2025-03-19 15:36 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +   their amount and compartment size.
```suggestion
   After the assignment of the target values, all derived variables, i.e. algebraic entities, are
   updated.
   
   * These updates respect language specific interpretations of which variables are *atomic* or *derived*/*algebraic*. For example, SBML considers concentrations to be *derived*, meaning that species concentrations will be recomputed based on (updated) values of species amounts and corresponding compartment sizes.
```

2025-03-19 15:39 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +The optional experiments table describes a sequence of different experimental
Would prefer making both tables optional over forcing the user to add empty dummies. Should be foolproof as the linter should catch missing experimentIds in the measurements table in case those tables were erroneously omitted.

2025-03-19 15:47 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +    :ref:`v2_parameters_table` (including ``estimate=0`` parameters).
If we move this bit below the introduction of differential/constant entities we could simply say differential and constant entities that are not assigned in the parameters table, independent of the assigned value in the estimate column.

2025-03-20 12:15 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +values of species, and compartments, during specific time periods.
Tried to do that...

2025-03-20 12:46 UTC, dweindl approved these changes

2025-03-20 18:10 UTC, matthiaskoenig commented
Hi all,
I just realized that for steady state simulations, i.e. experiments with `time=-inf` I don't completely understand how this would work with models which have time-dependent events.

Currently it reads; "Any event triggers defined in the model must also be checked during this pre-simulation."
- it should probably be specified that the model should be simulated to steady state from `time=0`.
- it should be mentioned that models which are simulated to steady state should not have any time dependent triggers (as I understand it this is not well defined; and steady state solvers properly don't handle this correctly). Also if there are time dependent events one would want to start with time!=0 to pre-equilibration which is currently not possible.

So not clear to me how things work with "-Inf" time and time-triggered events.

2025-03-20 18:24 UTC, dweindl commented
> * it should probably be specified that the model should be simulated to steady state from `time=0`.

Agreed that it would be good to state that explicitly. I'd say from $t_0=0$, unless the model has specified some other $t_0$.


> * it should be mentioned that models which are simulated to steady state should not have any time dependent triggers (as I understand it this is not well defined; and steady state solvers properly don't handle this correctly). Also if there are time dependent events one would want to start with time!=0 to pre-equilibration which is currently not possible.

This is not only a problem with time-triggered events, but with any event assignments that are executed after the initial timepoint. If the model has such constructs, directly solving for $dx/dt = 0$ usually won't work. Not sure if this needs to be stated explicitly. If users don't want their events triggered during the steady state simulation, they can simple switch them off by including some indicator variable in the trigger function.

2025-03-20 19:11 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +structure. That mean that only constant or differential entities (e.g.,
```suggestion
structure. That means that only constant or differential entities (e.g.,
```

2025-03-20 19:13 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  If the simulation of a condition with steady fails to reach a steady state,
```suggestion
  If the simulation of a condition with steady state fails to reach a steady state,
```

2025-03-20 19:15 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  ``time`` will override any initial time specified in the model.
```suggestion
  ``time`` will override any initial time specified in the model, except in the case of ``time`` =  `ìnf``, in which case the model-specified time will be used (or 0, if the model does not explicitly specify an initial time).
```

2025-03-20 19:17 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  Multiple conditions cannot be applied simultaneously within in a single
```suggestion
  Multiple conditions cannot be applied simultaneously within a single
```

2025-03-20 19:38 UTC, sebapersson commented on doc/v2/documentation_data_format.rst
> +- A :ref:`parameters file <v2_parameters_table>` defining estimable
To note close the door on Bayesians :), I would write 

I think parameters to be estimated or inferred.

2025-03-20 19:42 UTC, sebapersson commented on doc/v2/documentation_data_format.rst
> +| conditionId  | targetId                | targetValue        |
Second this that examples can help digest the standard.

2025-03-20 19:45 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +| conditionId  | targetId                | targetValue        |
Agreed, although in the longer run, I'd prefer some self-contained problem-specific HowTos / examples outside this document. I think this will be more useful.

2025-03-20 19:46 UTC, sebapersson approved these changes
Looks good, feel free to merge for me when some of the minor comments below are fixed.

2025-03-20 19:57 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  parameters and related information [TSV].
```suggestion
- A :ref:`parameters file <v2_parameters_table>` to set parameter values globally and to specify the parameters to be estimated as well as their parameter bounds and prior distributions [TSV].
```

2025-03-20 21:48 UTC, matthiaskoenig approved these changes

2025-03-21 07:24 UTC, fbergmann commented on doc/v2/gfx/petab_scope_and_files.png
@dweindl  should the measurement table not change to list an experimentId now rather than a timecourseId?

2025-03-21 07:25 UTC, fbergmann commented on doc/v2/gfx/petab_scope_and_files.svg
@dweindl same here

2025-03-21 08:58 UTC, dweindl commented on doc/v2/gfx/petab_scope_and_files.svg
Indeed. Thanks.

2025-03-21 09:10 UTC, dweindl commented on doc/v2/gfx/petab_scope_and_files.png
fixed.

2025-03-21 09:13 UTC, matthiaskoenig reviewed
The parameter value of the upper bound 250 in the parameter table is not a number:
25o -> 250

2025-03-21 13:09 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  model that are not targets of rate rules or assignment rules.
It's unclear that algebraic assignments like SBML initialAssignmentRules are constant entities. I'm not sure how to best word that here. In PEtab SciML there is an attempt at distinguishing these by calling this "prior to simulation". I guess the difference between algebraic entities and constant entities is that constant entities are piecewise constant (e.g. initialAssignmentRules or eventAssignments can affect them, but otherwise they are constant), and algebraic entities are everything else.

2025-03-21 13:26 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
Since this is a user's choice, I don't think we need to specify that the simulation stops at the last measurement. A tool might want to give users an easier way to perform predictions, than providing a dummy measurements table.

2025-03-21 13:32 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +The conditions table defines discrete changes to the model. These (sets of)
To match the start of the Experiments table section

```suggestion
The optional conditions table defines discrete changes to the model. These (sets of)
```

2025-03-21 13:33 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  (:ref:`v2_experiments_table`).
And also now optional, if the user wants to simulate the SBML model as-is

2025-03-21 13:36 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> ++---------------------+-------------------+-----------------+
To match the conditions table section

```suggestion
+---------------------+-------------------+-----------------+
| experimentId        | time              | conditionId     |
+=====================+===================+=================+
| PETAB_ID            | NUMERIC or '-inf' | CONDITION_ID    |
+---------------------+-------------------+-----------------+
| e.g.                |                   |                 |
+---------------------+-------------------+-----------------+
| timecourse_1        |                 0 | condition_1     |
+---------------------+-------------------+-----------------+
```

2025-03-21 13:36 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +The time courses table has three mandatory columns ``experimentId``,
```suggestion
The experiment table has three mandatory columns ``experimentId``,
```

2025-03-21 13:37 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  experiment; each ``time`` values must be unique for each ``experimentId``.
```suggestion
  Multiple conditions cannot be applied simultaneously within a single
  experiment; each ``time`` value must be unique for each ``experimentId``.
```

2025-03-21 13:39 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  time).
```suggestion
  ``time`` will override any initial time specified in the model,
  except in the case of ``time`` =  ``-ìnf``, in which case the model-specified
  time will be used (or 0, if the model does not explicitly specify an initial
  time).
```

2025-03-21 13:40 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  [PETAB_ID or empty, REQUIRED, REFERENCES(condition.conditionId)]
```suggestion
- ``conditionId``:
  [CONDITION_ID or empty, REQUIRED, REFERENCES(condition.conditionId)]
```

2025-03-21 13:43 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  [PETAB_ID or empty, REQUIRED, REFERENCES(condition.conditionId)]
Hm not sure if this is correct. I guess it should be "PETAB_ID", but the table above it says "CONDITION_ID".

2025-03-21 13:46 UTC, dilpath commented on doc/v2/documentation_data_format.rst
>  | STRING      | [STRING]        | log10\|lin\|log         | NUMERIC     | NUMERIC    | NUMERIC      | 0\|1     | ... |
```suggestion
| PETAB_ID      | [STRING]        | log10\|lin\|log         | NUMERIC     | NUMERIC    | NUMERIC      | 0\|1     | ... |
```

2025-03-21 13:46 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +| STRING        | STRING        | STRING        |
```suggestion
| PETAB_ID        | STRING        | STRING        |
```

2025-03-21 13:49 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
Change to "between the last time point and the end of the simulation" ?

2025-03-21 13:54 UTC, FFroehlich commented on doc/v2/documentation_data_format.rst
> +The time courses table has three mandatory columns ``experimentId``,
experiment*s*

2025-03-21 14:14 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  model that are not targets of rate rules or assignment rules.
The thing that is unclear to me is that both of these are algebraic, but one is compatible with "constant entity" whereas the other is not:
- initialAssignmentRule is an algebraic equation that is evaluated at one time point
- assignmentRule is an algebraic equation that is evaluated throughout time

2025-03-21 14:16 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +  model that are not targets of rate rules or assignment rules.
I tried to rephrase it, please check again.

2025-03-21 14:17 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
Updated.

2025-03-21 14:18 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +The time courses table has three mandatory columns ``experimentId``,
"Experiment table" in the figure, but fine for me

2025-03-21 14:21 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +The time courses table has three mandatory columns ``experimentId``,
I think that is inconsistent throughout the documentation, library, ...
Let's address that separately and get this monster merged and out of the way.

2025-03-21 14:26 UTC, dilpath commented on doc/v2/documentation_data_format.rst
> +  model that are not targets of rate rules or assignment rules.
Looks good, the intention of the different entities is clear now :+1: Thanks

2025-03-21 14:43 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
I could imagine adding an empty time interval at the end without any condition with the time>last timepoint. I.e. one could have a time interval at the end where no measurements exist. In this case the simulation has to run until the last specified time point of the experiment.
This should be clarified and would provide a simple manner to encode the end of the simulation if one wants, e.g. for visualization or other purposes.

2025-03-21 14:52 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
I'd consider that out of scope here. For the purpose of parameter estimation, tools can just stop at the last measurement timepoint.

Your use case would have to be addressed in some visualization function. For proper visualization, additional information such as the output timepoints would be required. I don't think we should try to get that in here.

2025-03-21 15:15 UTC, matthiaskoenig commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
Or could I just add a dummy timepoint to the measurement table with a NaN value at the end?

2025-03-21 15:28 UTC, dweindl commented on doc/v2/documentation_data_format.rst
> +:ref:`v2_measurements_table`.
> Or could I just add a dummy timepoint to the measurement table with a NaN value at the end?

That would currently be considered an error. NaN is not allowed. We had that implemented at some point, but it's an abuse of the measurements table. We can continue that discussion outside this PR if you'd consider it important to change that.

If the only purpose is visualization, I'd rather specify the endpoint and potentially time-resolution in the visualization table (or any better replacement of that...). 

Let's get this thing here merged and revisit any revision of visualization-related functionality afterwards?

2025-03-24 20:42 UTC, merged